apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../apps/
- sync.yaml
images:
- name: ghcr.io/stefanprodan/podinfo
  newTag: 6.1.7
patches:
- patch: |-
    - op: replace
      path: /spec/chart/spec/version
      value: 6.1.7
  target:
    kind: HelmRelease
    name: podinfo-pipeline-helm
