apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../apps
images:
- name: ghcr.io/stefanprodan/podinfo
  newTag: 6.1.8
patches:
- patch: |-
    - op: replace
      path: /spec/chart/spec/version
      value: 6.1.8
  target:
    kind: HelmRelease
    name: podinfo-pipeline-helm
