---
apiVersion: wego.weave.works/v1alpha2
kind: Pipeline
metadata:
  name: example-pipeline
  namespace: flux-system
spec:
  stages:
    - name: dev
      namespace: dev
      order: 1
      releaseRef:
        name: podinfo-pipeline-helm
        kind: HelmRelease
    # - name: staging
    #   namespace: staging
    #   order: 2
    # - name: prod
    #   namespace: prod
    #   order: 3
