apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipelines
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/rparmer/pipelines
  ref:
    branch: full-crd
