apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipelines
spec:
  interval: 5m
  url: https://github.com/rparmer/pipelines
  ref:
    branch: kustomizations
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-pipelines
  labels:
    pipelines.wego.weave.works/name: example-pipeline
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: pipelines
  path: "./demo/apps/kustomization/podinfo"
  prune: true
